cp ../Ulrike/intermission/extravaganza-titlepage.mp4                    1.mp4
cp ../Ulrike/choir/choir.mp4                                            2.mp4
cp ../Ulrike/intermission/extravaganza-intermission-bat.mp4             3.mp4
cp ../samcarter/Bat/bat.mp4                                             4.mp4
cp ../Ulrike/intermission/extravaganza-intermission-hippos.mp4          5.mp4
cp ../Ulrike/Hippos/hippos.mp4                                          6.mp4
cp ../Ulrike/intermission/extravaganza-intermission-goodbye.mp4         7.mp4
cp ../Ulrike/goodbye/goodbye.mp4                                        8.mp4
cp ../Ulrike/intermission/extravaganza-intermission-wildwest.mp4        9.mp4
cp ../Ulrike/WildWest/wildwest.mp4                                      10.mp4
cp ../Ulrike/intermission/extravaganza-intermission-arts.mp4            11.mp4
cp ../samcarter/Museum/Museum.mp4                                       12.mp4
cp ../Ulrike/intermission/extravaganza-intermission-ctan.mp4            13.mp4
cp ../samcarter/Ctan/ctan.mp4                                           14.mp4
cp ../Ulrike/intermission/extravaganza-intermission-different-tug.mp4   15.mp4
cp ../samcarter/tug/tug.mp4                                             16.mp4
cp ../Ulrike/intermission/extravaganza-intermission-island.mp4          17.mp4
cp ../Ulrike/Island/Island.mp4                                          18.mp4
cp ../Ulrike/intermission/extravaganza-intermission-italiana.mp4        19.mp4
cp ../Carla/Bella_Italia/BellaItalia.mp4                                20.mp4
cp ../Ulrike/intermission/extravaganza-intermission-twitter.mp4         21.mp4
cp ../samcarter/twitter/twitter.mp4                                     22.mp4
cp ../Ulrike/intermission/extravaganza-intermission-cat.mp4             23.mp4
cp ../samcarter/Cats/Cats.mp4                                           24.mp4
cp ../Ulrike/intermission/extravaganza-intermission-particleduck.mp4    25.mp4
cp ../Paulo/particleman/particleman.mp4                                 26.mp4
cp ../Ulrike/intermission/extravaganza-intermission-night.mp4           27.mp4
cp ../samcarter/NightDivine/NIghtDivine.mp4                             28.mp4
cp ../Ulrike/intermission/extravaganza-intermission-finale.mp4          29.mp4
cp ../Ulrike/Finale/finale.mp4                                          30.mp4
cp ../Ulrike/intermission/extravaganza-2019-credits.mp4                 31.mp4
cp ../Ulrike/intermission/extravaganza-intermission-postcredits.mp4     32.mp4
cp ../Paulo/postcredits/postcredits43.mp4                               33.mp4